/**
 * Starter exercise library. Deliberately broad — from barbell work through to
 * chair-based movements — so there's something usable whoever you're writing
 * a week for. Add, edit and delete freely from /admin/library.
 *
 * `mode: 'time'` entries use `duration`; `mode: 'reps'` entries use `reps`.
 */
export const LIBRARY = [
  // ------------------------------------------------------------------ Legs
  { name: 'Bodyweight squat', category: 'Legs', sets: 3, reps: 10, rest: 45,
    instructions: 'Feet about shoulder-width apart. Sit your hips back and down as if reaching for a chair, then stand tall. Keep your heels down.' },
  { name: 'Chair squat', category: 'Legs', sets: 3, reps: 8, rest: 45,
    instructions: 'Stand in front of a chair. Lower until you just touch the seat, then stand back up without fully sitting.' },
  { name: 'Sit to stand', category: 'Legs', sets: 2, reps: 8, rest: 45,
    instructions: 'Sit tall at the front of a sturdy chair, feet flat. Stand without pushing off with your hands, then lower yourself down slowly.' },
  { name: 'Goblet squat', category: 'Legs', sets: 3, reps: 10, rest: 60,
    instructions: 'Hold a dumbbell or kettlebell at your chest. Squat down between your knees, keeping your chest up.' },
  { name: 'Forward lunge', category: 'Legs', sets: 3, reps: 8, rest: 60,
    instructions: 'Step forward and lower your back knee towards the floor. Push through the front heel to return. Alternate legs.' },
  { name: 'Reverse lunge', category: 'Legs', sets: 3, reps: 8, rest: 60,
    instructions: 'Step backwards and lower your back knee. Easier on the knees than a forward lunge. Alternate legs.' },
  { name: 'Split squat', category: 'Legs', sets: 3, reps: 8, rest: 60,
    instructions: 'One foot forward, one back, staying in place. Lower straight down, then push back up. Swap legs each set.' },
  { name: 'Step-up', category: 'Legs', sets: 3, reps: 10, rest: 60,
    instructions: 'Step onto a low step leading with one foot, then step down under control. Hold a rail if you need to.' },
  { name: 'Deadlift', category: 'Legs', sets: 3, reps: 8, rest: 90,
    instructions: 'Hinge at the hips with a flat back, grip the bar, then stand up by driving through your heels. Keep the bar close to your legs.' },
  { name: 'Romanian deadlift', category: 'Legs', sets: 3, reps: 10, rest: 75,
    instructions: 'Soft knees, push your hips back and lower the weight down your thighs. Stop when you feel a stretch in the hamstrings, then stand tall.' },
  { name: 'Single-leg deadlift', category: 'Legs', sets: 2, reps: 8, rest: 60,
    instructions: 'Stand on one leg, hinge forward and let the other leg travel back behind you. Hold something for balance if needed. Swap sides.' },
  { name: 'Glute bridge', category: 'Legs', sets: 3, reps: 12, rest: 45,
    instructions: 'Lie on your back, knees bent, feet flat. Squeeze your glutes and lift your hips, then lower slowly.' },
  { name: 'Hip thrust', category: 'Legs', sets: 3, reps: 10, rest: 60,
    instructions: 'Upper back against a bench, weight across the hips. Drive your hips up until your body is level, then lower.' },
  { name: 'Heel raise', category: 'Legs', sets: 2, reps: 12, rest: 30,
    instructions: 'Hold a chair or wall. Rise onto your toes, hold for a second, then lower slowly.' },
  { name: 'Wall sit', category: 'Legs', mode: 'time', sets: 2, duration: 30, rest: 45,
    instructions: 'Back against a wall, slide down until your knees are bent comfortably. Hold. Come up sooner if your knees complain.' },
  { name: 'Leg press', category: 'Legs', sets: 3, reps: 10, rest: 75,
    instructions: 'Feet flat on the platform, lower under control, then press away without locking the knees hard.' },

  // ------------------------------------------------------------ Upper body
  { name: 'Push-up', category: 'Upper body', sets: 3, reps: 8, rest: 60,
    instructions: 'Hands under your shoulders, body in a straight line. Lower your chest, then push back up. Knees down is a fine version.' },
  { name: 'Wall push-up', category: 'Upper body', sets: 2, reps: 8, rest: 45,
    instructions: "Stand an arm's length from a wall, hands flat at shoulder height. Bend your elbows to bring your chest towards the wall, then push back." },
  { name: 'Incline push-up', category: 'Upper body', sets: 3, reps: 10, rest: 45,
    instructions: 'Hands on a bench or worktop. The higher the surface, the easier it is.' },
  { name: 'Bench press', category: 'Upper body', sets: 3, reps: 8, rest: 90,
    instructions: 'Lower the bar to your chest under control, then press up. Use a spotter for heavy sets.' },
  { name: 'Dumbbell chest press', category: 'Upper body', sets: 3, reps: 10, rest: 60,
    instructions: 'Lying on a bench or the floor, press the dumbbells up over your chest, then lower slowly.' },
  { name: 'Overhead press', category: 'Upper body', sets: 3, reps: 8, rest: 75,
    instructions: 'Press the weight from shoulder height to overhead without arching your lower back.' },
  { name: 'Lateral raise', category: 'Upper body', sets: 3, reps: 12, rest: 45,
    instructions: 'Light weights. Raise your arms out to the sides to shoulder height, then lower slowly.' },
  { name: 'Front raise', category: 'Upper body', sets: 2, reps: 12, rest: 45,
    instructions: 'Raise the weights straight out in front to shoulder height, then lower under control.' },
  { name: 'Overhead reach', category: 'Upper body', sets: 2, reps: 8, rest: 30,
    instructions: 'Sitting or standing tall, reach both arms up above your head. Only go as high as feels comfortable.' },
  { name: 'Bicep curl', category: 'Upper body', sets: 3, reps: 10, rest: 45,
    instructions: 'Arms by your sides, bend at the elbow to bring the weight up, then lower slowly. Water bottles work fine.' },
  { name: 'Tricep extension', category: 'Upper body', sets: 3, reps: 10, rest: 45,
    instructions: 'Weight behind your head, elbows pointing up. Straighten your arms, then lower under control.' },
  { name: 'Tricep dip', category: 'Upper body', sets: 3, reps: 8, rest: 60,
    instructions: 'Hands on the edge of a sturdy chair, feet out in front. Bend your elbows to lower, then press back up.' },
  { name: 'Bent-over row', category: 'Upper body', sets: 3, reps: 10, rest: 60,
    instructions: 'Hinge forward with a flat back. Pull the weight to your ribs, squeezing your shoulder blades, then lower.' },
  { name: 'Dumbbell row', category: 'Upper body', sets: 3, reps: 10, rest: 60,
    instructions: 'One hand and knee on a bench. Pull the dumbbell up to your side, then lower slowly. Swap sides.' },
  { name: 'Lat pulldown', category: 'Upper body', sets: 3, reps: 10, rest: 60,
    instructions: 'Pull the bar down to your upper chest, leading with your elbows. Control it back up.' },
  { name: 'Pull-up', category: 'Upper body', sets: 3, reps: 5, rest: 90,
    instructions: 'Hang from the bar and pull your chin above it. Use a band or an assisted machine if needed.' },
  { name: 'Face pull', category: 'Upper body', sets: 3, reps: 12, rest: 45,
    instructions: 'Pull a cable or band towards your face, elbows high. Good for posture and shoulder health.' },
  { name: 'Reverse fly', category: 'Upper body', sets: 3, reps: 12, rest: 45,
    instructions: 'Hinge forward, light weights. Open your arms out to the sides, squeezing your shoulder blades.' },
  { name: 'Shoulder blade squeeze', category: 'Upper body', sets: 2, reps: 12, rest: 30,
    instructions: 'Sit or stand tall. Draw your shoulder blades together and down, hold for two seconds, release.' },
  { name: 'Wall angel', category: 'Upper body', sets: 2, reps: 8, rest: 45,
    instructions: 'Back against a wall, arms bent like goalposts. Slide your arms up and down, keeping contact with the wall.' },

  // ------------------------------------------------------------------ Core
  { name: 'Plank', category: 'Core', mode: 'time', sets: 3, duration: 30, rest: 45,
    instructions: 'Forearms and toes on the floor, body in a straight line. Squeeze your glutes. Drop to your knees if your back sags.' },
  { name: 'Side plank', category: 'Core', mode: 'time', sets: 2, duration: 20, rest: 45,
    instructions: 'On one forearm, hips lifted, body in a line. Swap sides between sets. Knees down makes it easier.' },
  { name: 'Dead bug', category: 'Core', sets: 3, reps: 10, rest: 45,
    instructions: 'On your back, arms up, knees bent. Lower one arm and the opposite leg, then swap. Keep your lower back down.' },
  { name: 'Bird dog', category: 'Core', sets: 3, reps: 10, rest: 45,
    instructions: 'On hands and knees, extend one arm and the opposite leg. Hold briefly, then swap.' },
  { name: 'Sit-up', category: 'Core', sets: 3, reps: 12, rest: 45,
    instructions: 'Knees bent, feet flat. Curl up towards your knees, then lower slowly.' },
  { name: 'Crunch', category: 'Core', sets: 3, reps: 15, rest: 30,
    instructions: 'Lift just your shoulder blades off the floor. Small movement, no pulling on your neck.' },
  { name: 'Russian twist', category: 'Core', sets: 3, reps: 16, rest: 45,
    instructions: 'Sit leaning back slightly, feet up or down. Rotate your torso side to side.' },
  { name: 'Leg raise', category: 'Core', sets: 3, reps: 10, rest: 45,
    instructions: 'On your back, legs straight. Lift them towards the ceiling, then lower slowly without arching your back.' },
  { name: 'Pallof press', category: 'Core', sets: 3, reps: 10, rest: 45,
    instructions: 'Band or cable at chest height, standing side-on. Press straight out and resist the twist. Swap sides.' },
  { name: 'Seated twist', category: 'Core', mode: 'time', sets: 2, duration: 30, rest: 30,
    instructions: 'Sit tall. Turn your upper body to one side, resting a hand on the chair back. Hold, breathe, then swap sides.' },

  // --------------------------------------------------------------- Balance
  { name: 'One-leg balance', category: 'Balance', mode: 'time', sets: 2, duration: 20, rest: 30,
    instructions: 'Hold a chair with one hand. Lift one foot slightly off the floor. Swap legs between sets.' },
  { name: 'Tandem stand', category: 'Balance', mode: 'time', sets: 2, duration: 30, rest: 30,
    instructions: 'One foot directly in front of the other, heel to toe. Hold a worktop for support. Swap which foot leads.' },
  { name: 'Heel-to-toe walk', category: 'Balance', sets: 2, reps: 10, rest: 30,
    instructions: 'Walk in a straight line placing your heel right in front of your other toes. Stay near a wall.' },
  { name: 'Standing march', category: 'Balance', mode: 'time', sets: 2, duration: 30, rest: 30,
    instructions: 'Holding a chair, lift one knee then the other, like marching on the spot. Steady rather than fast.' },
  { name: 'Side leg raise', category: 'Balance', sets: 2, reps: 12, rest: 30,
    instructions: 'Hold a chair. Lift one leg out to the side, keeping your body upright. Swap sides.' },
  { name: 'Clock reach', category: 'Balance', sets: 2, reps: 8, rest: 45,
    instructions: 'Stand on one leg holding support. Reach the other foot forward, out to the side, then behind, like clock hands.' },

  // -------------------------------------------------------------- Mobility
  { name: 'Cat-cow', category: 'Mobility', sets: 2, reps: 8, rest: 30,
    instructions: 'Hands on knees or on all fours. Arch your back and look up, then round your back and tuck your chin. Move with your breath.' },
  { name: 'Thoracic rotation', category: 'Mobility', sets: 2, reps: 8, rest: 30,
    instructions: 'On your side, knees bent. Open your top arm across your body and follow it with your eyes. Swap sides.' },
  { name: 'Hip flexor stretch', category: 'Mobility', mode: 'time', sets: 2, duration: 30, rest: 20,
    instructions: 'Half-kneeling, tuck your hips under and lean forward gently. Feel it at the front of the back hip. Swap sides.' },
  { name: 'Hamstring stretch', category: 'Mobility', mode: 'time', sets: 2, duration: 30, rest: 20,
    instructions: 'Heel on a low step, leg straight, hinge forward from the hips with a flat back. Swap sides.' },
  { name: 'Calf stretch', category: 'Mobility', mode: 'time', sets: 2, duration: 30, rest: 20,
    instructions: 'Hands on a wall, one leg back with the heel down. Lean in until you feel the calf stretch. Swap sides.' },
  { name: 'Doorway chest stretch', category: 'Mobility', mode: 'time', sets: 2, duration: 30, rest: 20,
    instructions: 'Forearm on a door frame, step gently through until you feel a stretch across the chest. Swap sides.' },
  { name: 'Shoulder rolls', category: 'Mobility', sets: 1, reps: 10, rest: 20,
    instructions: 'Roll both shoulders backwards in a big slow circle. Then ten forwards.' },
  { name: 'Neck turns', category: 'Mobility', sets: 1, reps: 6, rest: 20,
    instructions: 'Turn your head slowly to look over one shoulder, then the other. Never force it.' },
  { name: 'Ankle circles', category: 'Mobility', sets: 2, reps: 10, rest: 20,
    instructions: 'Sitting down, lift one foot and draw slow circles with your toes. Swap feet.' },
  { name: "Child's pose", category: 'Mobility', mode: 'time', sets: 2, duration: 30, rest: 20,
    instructions: 'Kneel and sit back onto your heels, reaching your arms forward along the floor. Breathe.' },
  { name: 'Figure-4 stretch', category: 'Mobility', mode: 'time', sets: 2, duration: 30, rest: 20,
    instructions: 'Ankle crossed over the opposite knee, gently draw the leg towards you. Swap sides.' },

  // ---------------------------------------------------------------- Cardio
  { name: 'Walk', category: 'Cardio', mode: 'time', sets: 1, duration: 1200, rest: 0,
    instructions: 'An easy pace where you can still hold a conversation.' },
  { name: 'Brisk walk', category: 'Cardio', mode: 'time', sets: 1, duration: 600, rest: 60,
    instructions: 'Pick the pace up a little — breathing harder, but still able to talk. Slow down whenever you want to.' },
  { name: 'Marching on the spot', category: 'Cardio', mode: 'time', sets: 2, duration: 60, rest: 30,
    instructions: 'March on the spot, lifting your knees. Swing your arms. Hold a chair if you prefer.' },
  { name: 'Stationary bike', category: 'Cardio', mode: 'time', sets: 1, duration: 900, rest: 0,
    instructions: 'Steady, comfortable resistance. Adjust the seat so your leg is almost straight at the bottom.' },
  { name: 'Rowing machine', category: 'Cardio', mode: 'time', sets: 1, duration: 600, rest: 60,
    instructions: 'Drive with the legs first, then lean back, then pull the handle in. Reverse that order coming forward.' },
  { name: 'Stair climbing', category: 'Cardio', mode: 'time', sets: 2, duration: 120, rest: 60,
    instructions: 'Up and down a flight at a steady pace, holding the rail. Stop if you feel out of breath.' },
  { name: 'Swimming', category: 'Cardio', mode: 'time', sets: 1, duration: 1200, rest: 0,
    instructions: 'Any stroke you like, easy pace. Gentle on the joints.' },
  { name: 'Deep breathing', category: 'Cardio', mode: 'time', sets: 2, duration: 60, rest: 20,
    instructions: 'Sit down. Breathe in through your nose for four counts, out through your mouth for six.' },
];

/** Expands the compact rows above into full database records. */
export function toRecords(rows) {
  return rows.map((row) => {
    const mode = row.mode === 'time' ? 'time' : 'reps';
    return {
      name: row.name,
      category: row.category,
      instructions: row.instructions ?? '',
      mode,
      sets: row.sets ?? 1,
      reps: mode === 'reps' ? (row.reps ?? 10) : null,
      duration_seconds: mode === 'time' ? (row.duration ?? 30) : null,
      rest_seconds: row.rest ?? 30,
      media_type: 'none',
      media_url: '',
    };
  });
}
